ilastik:
  model: models/40x_pmc_seg.ilp
  loc: /home/dakota/Downloads/ilastik-1.3.3post3-Linux/run_ilastik.sh
input:
  logfile: /home/dakota/Data/icat_embryos/Nahomie/Nahomie_icat_embryo_log.csv
  datadir: /home/dakota/Data/icat_embryos/Nahomie
  skip: ['MK886_MK-1-7_groupA_18-MK-1-7-emb1002']
output:
  dir: data/
quant:
  genes:
    sm50:
      radius: [750, 500, 500]
    pks2:
      radius: [750, 500, 500]